name: Angle Render Worker

on:
  workflow_dispatch:
    inputs:
      code_url:
        description: "URL to user Python code file"
        required: true
      prompt_id:
        description: "Prompt ID"
        required: true
      project_id:
        description: "Project ID"
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anonlegionoke/angle-render-worker:latest
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download User Code
        run: curl -L -o user_code.py "${{ github.event.inputs.code_url }}"

      - name: Run Worker
        env:
          CODE_FILE: user_code.py
          PROMPT_ID: ${{ github.event.inputs.prompt_id }}
          PROJECT_ID: ${{ github.event.inputs.project_id }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
          SUPABASE_FRAMES_BUCKET: ${{ secrets.SUPABASE_FRAMES_BUCKET }}
          STORAGE_DIR: ${{ secrets.STORAGE_DIR }}
        run: python video_worker.py